## ALL IMPORTANT FUNCTIONS IN NUMPY PYTHON LIBRARAY FOR DATA ANALYSTS

# START

### INPORTING NUMPY PYTHON LIBRARY

In [1]:
import numpy as np

### ARRAYS CREATION METHOS
array function is used to create 1D 2D and 3D arrays


1D arrays

In [8]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(a)
print(b)

[1 2 3 4]
[5 6 7 8]


2D arrays

In [49]:

c=np.array([[1,2],[3,4]])
print(c)

[[1 2]
 [3 4]]


3D arrays

In [50]:
d=np.array([[[1,2,3],
             [4,5,6],
             [7,8,9]]])
print(d)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


range function for creating array 

In [45]:
a=np.arange(0,10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


linspace function for creating evenly spaced array between given numbers

In [46]:
l=np.linspace(1,2,5)
print(l)

[1.   1.25 1.5  1.75 2.  ]


zeros function gives the array wihch contains all elements as zeros

In [47]:
z=np.zeros(5)
print(z)

[0. 0. 0. 0. 0.]


In [48]:
z=np.zeros([3,3])
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Ones function is used to create the array with all elements as one

In [51]:
o=np.ones(5)
print(o)

[1. 1. 1. 1. 1.]


In [52]:
o=np.ones([3,3])
print(o)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


identity matrix is the matrix with even rows and columns and cross elements are ones

In [54]:
i=np.eye(2,2)
print(i)

[[1. 0.]
 [0. 1.]]


### ARRAYS ATTRIBUTES

attributes are the arrays properties such as size shape datatype dimension bytes size etc

In [55]:
a1=np.array([1,2,3,4])
a2=np.array([[1,2],
             [3,4]])
a3=np.array([[[1,2,3],
              [4,5,6],
              [7,8,9]]])
print(a1)
print(a2)
print(a3)

[1 2 3 4]
[[1 2]
 [3 4]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


shape function is the attribute which gives the number of elements in 1d arrays number of rosws and columns in 2d arrays and blocks rows and columns in 3d arrays 

In [56]:
as1=np.shape(a1)
as2=np.shape(a2)
as3=np.shape(a3)
print(as1)
print(as2)
print(as3)

(4,)
(2, 2)
(1, 3, 3)


ndim is the function which gives the diemnsion of the array

In [57]:
as1=np.ndim(a1)
as2=np.ndim(a2)
as3=np.ndim(a3)
print(as1)
print(as2)
print(as3)

1
2
3


size is the function which gives the total number of elements of the array

In [58]:
as1=np.size(a1)
as2=np.size(a2)
as3=np.size(a3)
print(as1)
print(as2)
print(as3)

4
4
9


itemsize is the function which is used to get the bytes occupied by a single element of the array

In [59]:
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

8
8
8


nbytes is the function which gives the total size of the array in bytes which is product of number of item*size of single element in bytes

In [60]:
print(a1.nbytes)
print(a2.nbytes)
print(a3.nbytes)

32
32
72


### INDEXING AND SLICING IN ARRAY

In [61]:
a1=np.array([1,2,3,4])
a2=np.array([[1,2],
             [3,4]])
a3=np.array([[[1,2,3],
              [4,5,6],
              [7,8,9]]])
print(a1)
print(a2)
print(a3)

[1 2 3 4]
[[1 2]
 [3 4]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


indexing in 1D arrays

In [64]:
print(a1[0])
print(a1[1])
print(a1[2])
print(a1[3])

1
2
3
4


INDEXING IN ARRAYS: Indexing in arrays means accessing fthe elements of the array at a particular position and the position is called as index. Indexing in array starts from 0 and goes till n-1 where n is total elements of the array

indexing in 2D arrays

In [66]:
print(a2[0,0])
print(a2[0,1])
print(a2[1,0])
print(a2[1,1])

1
2
3
4


indexing in 3D array

In [68]:
a3=np.array([[[1,2,3],
              [4,5,6],
              [7,8,9]]])
print(a3[0,0,0])
print(a3[0,0,1])
print(a3[0,0,2])
print(a3[0,1,0])
print(a3[0,1,1])
print(a3[0,1,2])
print(a3[0,2,0])
print(a3[0,2,1])
print(a3[0,2,2])

1
2
3
4
5
6
7
8
9


SLICING IN ARRAYS: slicing in arrays means accessing only some part of the array as a slice 

Slicing in 1D array: slicing contains three arguments array[start:stop:step]

In [3]:
a=np.array([1,2,3,4,5])
print(a[0::2])

[1 3 5]


Slciing in 2D arrays: Slicing in 2D arrays consists of rows and columns as arguments which inturn have start stop and step values as agruments

In [7]:
m=np.array([[1,2],
            [3,4],
            [5,5]])
print(m[0:1,0:2])

[[1 2]]


slicing in 3D array: when slicing in 3d array the arguments are blocks,rows and columns array[block:row:column] and rows and columns have their own arguments such as start stop and step

In [13]:
a=np.array([[[1,2,3],[4,5,6]],
            [[1,2,3],[4,5,6]],
            ])
print(a[0:1,0:1,0:2])

[[[1 2]]]


### ARRAY OPERATIONS (VECTORIZATION)

### arthmetic operations in numpy arrays

Array operations in one dimensional array such as addition,substraction multiplication division and modulus 

In [17]:
a=np.array([1,2,3,4])
b=np.array([4,5,6,8])
print(a)
print(b)
c=a+b
d=a-b
e=a*b
f=a/b
g=a//b
h=a%b
print(c)
print(d)
print(e)
print(f)
print(g)
print(h)              

[1 2 3 4]
[4 5 6 8]
[ 5  7  9 12]
[-3 -3 -3 -4]
[ 4 10 18 32]
[0.25 0.4  0.5  0.5 ]
[0 0 0 0]
[1 2 3 4]


Array operations in two dimensional array such as addition,substraction multiplication division and modulus 

In [19]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[10,11,12],[13,14,15],[16,17,18]])
print(a)
print(b)
c=a+b
d=a-b
e=a*b
f=a/b
g=a//b
h=a%b
print(c)
print(d)
print(e)
print(f)
print(g)
print(h)              

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[11 13 15]
 [17 19 21]
 [23 25 27]]
[[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]
[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]
[[0.1        0.18181818 0.25      ]
 [0.30769231 0.35714286 0.4       ]
 [0.4375     0.47058824 0.5       ]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Array operations in three dimensional array such as addition,substraction multiplication division and modulus 

In [25]:
a=np.array([[[1,2],[3,4]],
            [[5,6],[7,8]]])
b=np.array([[[9,10],[11,12]],
            [[13,14],[15,16]]])
c=a+b
d=a-b
e=a*b
f=a/b
g=a//b
h=a%b
print(c)
print(d)
print(e)
print(f)
print(g)
print(h)              

[[[10 12]
  [14 16]]

 [[18 20]
  [22 24]]]
[[[-8 -8]
  [-8 -8]]

 [[-8 -8]
  [-8 -8]]]
[[[  9  20]
  [ 33  48]]

 [[ 65  84]
  [105 128]]]
[[[0.11111111 0.2       ]
  [0.27272727 0.33333333]]

 [[0.38461538 0.42857143]
  [0.46666667 0.5       ]]]
[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### BOOLEAN INDEXING
boolean indexing is used to filter the values in the array based on the certain condition and most commom ones are logical_and and logical_or

Logical_and function: when logical_and function is used on the array both the conditios must be satisfied for getting the result based on those two condition. If any one condition fails then it does not give output

In [9]:
mask=np.logical_and(a>2,a<6)
a[mask]

array([3, 4])

logical_or function: when logical_or function is used on the array both the conditios need not be satisfied for getting the result based on the true condition. If any one condition fails then also output will come based on the other true condition

In [10]:
mask=np.logical_or(a<2,a>1)
a[mask]

array([1, 2, 3, 4])

In [26]:
mask=np.logical_or(a<3,a>4)
mask
a[mask]

array([1, 2, 5, 6, 7, 8])

### STATISTICS FUNCTIONS
The functions such as mean median standard deviation sum max min cumsum cumprod etc comes in statistics fucntions 

mean: The mean is the average of the all the elements than dividing them by total element

In [28]:
a=np.array([1,2,3,4,5])
print(np.mean(a))

3.0


standard deviation : its the measure of how the data is spread across when compared to the mean of the array 

In [29]:
a=np.array([1,2,3,4,5])
print(np.std(a))

1.4142135623730951


Varience: Varience is the squareroor of the standard deviation

In [30]:
a=np.array([1,2,3,4,5])
print(np.var(a))

2.0


cumulative sum and product: cumulative sum or product is the running total or multiplication when used woith the arrayas given below 

In [32]:
a=np.array([1,2,3,4,5])
print(a)
print(np.cumsum(a))
print(np.cumprod(a))


[1 2 3 4 5]
[ 1  3  6 10 15]
[  1   2   6  24 120]


max and min function returns the max and minimum value from the array

In [33]:
a=np.array([1,2,3,4,5])
print(a)
print(np.max(a))
print(np.min(a))

[1 2 3 4 5]
5
1


The above statistics functions can be used for 1D 2D and 3D arrays as well

### random functions

In [14]:
r=np.random.rand(2,3)
r

array([[0.0385308 , 0.13324857, 0.12128853],
       [0.96434134, 0.15921094, 0.26803794]])

In [16]:
s=np.random.randn(2,2)
s

array([[-0.91441093,  0.51513492],
       [ 0.5816783 , -0.77033574]])

In [22]:
num=np.random.randint(1,10)
num

8

### nonzero fucntion
returns index of non zero elements from array

In [ ]:
ar=np.array([1,0,2,0,3,0])
n=np.nonzero(ar)
n
print(ar[n])a

[1 2 3]


### condtional statements 
where condtion- repalces the true and false value in array with given values 

In [40]:
a=np.array([1,2,3,4,5,6,7,8,9,0])
print(a)
result=np.where(a>5,'high','low')
result

[1 2 3 4 5 6 7 8 9 0]


array(['low', 'low', 'low', 'low', 'low', 'high', 'high', 'high', 'high',
       'low'], dtype='<U4')

argwhere condition- used to get the index of elements of array where condition is true

In [ ]:
m=np.argwhere(a>7)
m
a[m]

array([[8],
       [9]])

### ITERATORS IN NUMPY ARRAYS
there are two types of iterators in numpy arrays nditer and enerumitro 

nditer function : when we loop using this iterator in any array 1d 2d or 3d we will get the elements of the array 

In [ ]:
a=np.array([1,2,3,4,5,6,7,8,9,0])
for i in np.nditer(a):
    print(i)

1
2
3
4
5
6
7
8
9
0


ndenumerate function is used when you want the index and the value at that indext at once 

In [37]:
a=np.array([1,2,3,4,5,6,7,8,9,0])
for idx,val in np.ndenumerate(a):
    print(idx,val)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5
(5,) 6
(6,) 7
(7,) 8
(8,) 9
(9,) 0


### RESHAPING IN ARRAYS

reshaping of the arrays can be done in two ways using reshape and flatten function

reshape function: when the dimension of the array is changed using reshape function the reshaped array view of original and any changes made in reshaped array will reflect in original array

In [9]:
a=np.arange(0,10)
print(a)
reshape=np.reshape(a,[5,2])
print(reshape)
reshape[0,0]=1011
print(reshape)
print(a)

[0 1 2 3 4 5 6 7 8 9]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[1011    1]
 [   2    3]
 [   4    5]
 [   6    7]
 [   8    9]]
[1011    1    2    3    4    5    6    7    8    9]


flatten fucntion : when the flatten function is used to change the multi dimension array to one dimension array it creates the copy of the original array amd any chnages made to flatten array will not relfect in the original array

In [12]:
a=np.arange(0,10)
reshape=np.reshape(a,[5,2])
print(reshape)
flat=reshape.flatten()
print(flat)
flat[0]=200
print(flat)
print(a)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[0 1 2 3 4 5 6 7 8 9]
[200   1   2   3   4   5   6   7   8   9]
[0 1 2 3 4 5 6 7 8 9]


### STACKING IN NUMPY ARRAYS

stacking is when one array is stacked with another array to form the resultant array. Stacking can be horizontal stacking hstack and vertical stacking vstack

Hstack and Vstack in 1d arrays
hstack means horizontal stacking where array are stacked horizontally sider by side and number of columns increase for the resultant array. when we want to perform we must have same number of the rows. In vstack the arrays are stacked top to bottom and number of rows increases. For vstack the number of columns must be same 

hstack and vstack in 1d arrays

In [15]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
vstack=np.vstack([a,b])
hstack=np.hstack([a,b])
print(vstack)
print(hstack)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 1  2  3  4  5  6  7  8  9 10]


hstack and vstack in 2d arrays

In [18]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[10,11,12],[13,14,15],[16,17,18]])
vstack=np.vstack([a,b])
hstack=np.hstack([a,b])
print(vstack)
print(hstack)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


hstack and vstack in 3d array

In [17]:
a=np.array([[[1,2],[3,4]],
            [[5,6],[7,8]]])
b=np.array([[[9,10],[13,14]],
            [[11,12],[15,16]]])
vstack=np.vstack([a,b])
hstack=np.hstack([a,b])
print(vstack)
print(hstack)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [13 14]]

 [[11 12]
  [15 16]]]
[[[ 1  2]
  [ 3  4]
  [ 9 10]
  [13 14]]

 [[ 5  6]
  [ 7  8]
  [11 12]
  [15 16]]]


### REPEATING AND TILING IN NUMPY ARRAYS

repeat function: when you want to repeat every element of the array particular number of times then you use repeat function in numpy. it automatically flattens the array if axis is not specified 

repeating in 1d 2d and 3d arrays using repeat function

In [29]:
a=np.array([1,2,3])
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
c=np.array([[[1,2],[3,4]],
            [[5,6],[7,8]]])
rep1=np.repeat(a,2)
rep2=np.repeat(b,2,axis=0)
rep3=np.repeat(c,2,axis=1)
print(rep1)
print(rep2)
print(rep3)

[1 1 2 2 3 3]
[[1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]
 [7 8 9]
 [7 8 9]]
[[[1 2]
  [1 2]
  [3 4]
  [3 4]]

 [[5 6]
  [5 6]
  [7 8]
  [7 8]]]


Tiling in numpy arrays: when you want to repeat the entire array and not the elements then you use the tile function. Tiling is done horizontly 

In [30]:
a=np.array([1,2,3])
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
c=np.array([[[1,2],[3,4]],
            [[5,6],[7,8]]])
til1=np.tile(a,2)
til2=np.tile(b,2)
til3=np.tile(c,2)
print(til1)
print(til2)
print(til3)

[1 2 3 1 2 3]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]
[[[1 2 1 2]
  [3 4 3 4]]

 [[5 6 5 6]
  [7 8 7 8]]]


logspace function create the number of equal partitions with the range and the number of parts given as agruments when calling the function on the log10 scale

In [2]:
a=np.logspace(1,2,5)
print(a)

[ 10.          17.7827941   31.6227766   56.23413252 100.        ]


### BROADCASTING IN NUMPY ARRAYS

broadcasting means stretching the smaller array to match the shape of the bigger arrays for any mathematical calculations 

### RULES FOR BROADCASTING
RULE 1 numpy compares the shape of the two arrays from right to left. if shapes are equal both arrays are compatible for math operation and no need of broadcasting  if one array is onely have one element then that can be shretched to match the shape of other array

RULE 2:if 1 is there in shape of any one of the array then broadcasting can be performed to stretch it to match the other array and resultant array will have max rows and max columns as its shape 

RULE 3 if the array is not scaler array or if there is no 1 in the shape of any one array out of two arrays then broadcasting cannot be done 

when one of the two arrays is scaler 

In [2]:
a=50 
b=np.array([1,2,3])
r=a+b
print(r)

[51 52 53]


when one dof the two array has one in its shape

In [6]:
a=np.array([[1,2,3]])
b=np.array([[1],[2],[3]])
c=a+b
print(c)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


### VECTORIZATION IN ARRAYS

Vectorize function : when you want to create the function which is not inbuilt in numpy to perform some action on the each element of the entire array then you can create your function and vectorize it using the vectorize function. it can be used when you eant custom function to be applied on every element and its good for reqadibilty as well

In [8]:
def sqnum(a):
    return a*a
np.vectorize(sqnum)
a=np.array([1,2,3,4,5])
print(sqnum(a))

[ 1  4  9 16 25]


### INBUILT VECTORIZED FUNCTIONS IN NUMPY PYTHON LIBRARY

the vectorized functions are those functions which can perform a specific operation on each element of the array whether its 1d 2d or 3d array the good part is we do not need loops and its way faster. there are lot of numpy vectorized functions some of them are given below 

In [14]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.sum(a)
d=np.subtract(b,a)
e=np.multiply(a,b)
f=np.floor_divide(b,a)
g=np.divide(b,a)
h=np.power(a,b)
i=np.exp(a)
j=np.sqrt(a)
print(c)
print(d)
print(e)
print(f)
print(g)
print(h)
print(i)
print(j)


10
[4 4 4 4]
[ 5 12 21 32]
[5 3 2 2]
[5.         3.         2.33333333 2.        ]
[    1    64  2187 65536]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[1.         1.41421356 1.73205081 2.        ]


the above functions can be performed on 2d and 3d arrays as well and there are whole lot more vectorized function which you can use when needed 

### HANDLING MISSING VALUES USING NUMPY

when ever you are dealing with the real datasets you will not have complte date. some data might be missing and have null values and other may have invalid or grabage value stored in it



### NP.NAN
NAN stands for not a number. this is used to represent the null or the undefined values in the numpy arrays


In [15]:
a=np.array([1,2,3,4,np.nan,6,7,np.nan])
print(a)

[ 1.  2.  3.  4. nan  6.  7. nan]


### NP.INF AND -NP.INF
INF stands for infinite values so these two represents the positive and negitive infinte values in numpy arrays. these appear in the zrto division and overflow situations

In [16]:
b=np.array([1,2,3,4,np.inf,6,7,-np.inf])
print(a)

[ 1.  2.  3.  4. nan  6.  7. nan]


checking for special values such as nan,inf,-inf using numpy functions such as isnan isfinite and siinf which returns boolean values of true and false

In [17]:
nan=np.isnan(a)
print(nan)

[False False False False  True False False  True]


In [18]:
inf=np.isinf(b)
print(inf)

[False False False False  True False False  True]


In [19]:
finite=np.isfinite(b)
print(finite)

[ True  True  True  True False  True  True False]


### Replacing on removing nan inf and -inf values 
nan_to_num() function is used to replace the nan values with 0 positive infinite vslue with positive infinite number and negitive infinite values with negitive infinite numbers

In [20]:
nan=np.nan_to_num(a)
inf=np.nan_to_num(b)
print(nan)
print(inf)

[1. 2. 3. 4. 0. 6. 7. 0.]
[ 1.00000000e+000  2.00000000e+000  3.00000000e+000  4.00000000e+000
  1.79769313e+308  6.00000000e+000  7.00000000e+000 -1.79769313e+308]


# END